[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.build]
install_crate = "cargo-xbuild"
command = "cargo"
args = ["xbuild", "--release", "--target", "x86_64-none-uefi"]
dependencies = ["format"]

[tasks.test]
install_crate = "cargo-xbuild"
command = "cargo"
args = ["xtest", "--target", "x86_64-none-uefi"]
dependencies = ["format"]
