[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.kernel]
install_crate = "cargo-xbuild"
command = "cargo"
args = ["xbuild", "--release", "--target", "kernel/x86_64-aurOS-none.json"]
dependencies = ["format"]

[tasks.os_loader]
install_crate = "cargo-xbuild"
command = "cargo"
args = ["xbuild", "--release", "--target", "x86_64-none-uefi"]
dependencies = ["format"]

[tasks.build]
dependencies = ["kernel", "os_loader"]
# Add in stuff and things to build directory structure to run QEMU on

[tasks.kernel_test]
install_crate = "cargo-xbuild"
command = "cargo"
args = ["xtest", "--target", "kernel/x86_64-aurOS-none.json"]
dependencies = ["format"]

[tasks.os_loader_test]
install_crate = "cargo-xbuild"
command = "cargo"
args = ["xtest", "--target", "x86_64-none-uefi"]
dependencies = ["format"]

[tasks.test]
dependencies = ["kernel_test", "os_loader_test"]
